/* Author: Abdullah Ahmad
Date: Fall Semester 2019
Section: CSCE-121-532
UIN: 927009064
E-mail: abdullah2808@tamu.edu
Assignment 1: Learn Basic UNIX commands and run a c++ program through the terminal
*/

#include<iostream>  
  
using namespace std; 
  
// main function - 
// where the execution of program begins 
int main() 
{ 
    // prints hello world 
    cout<<"Hello World"; 
      
    return 0; 
} 